spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: ${EUREKA_SECURITY_USER_USERNAME}
      password: ${EUREKA_SECURITY_USER_PASSWORD}
  profiles:
    active: dev

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false