spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avaliador_credito
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate.default_schema: msclientes
  flyway:
    enabled: true
    schemas: msclientes
    default-schema: msclientes
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/mscourserealm}