spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avaliador_credito
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate.default_schema: msclientes
  flyway:
    enabled: true
    schemas: msclientes
    default-schema: msclientes
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8081/realms/mscourserealm

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:ecok-pass-word-vai1@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost