spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8081/realms/mscourserealm

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cursoms-eureka-user:ecok-pass-word-vai1@localhost:8761/eureka
