spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:bootstrap}
    password: ${SPRING_RABBITMQ_PASSWORD:bootstrap}
  datasource:
    url: ${POSTGRES_DATASOURCE_URL}
    username: ${POSTGRES_DATASOURCE_USERNAME}
    password: ${POSTGRES_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    schemas: mscartoes
    default-schema: mscartoes
  jpa:
    properties:
      hibernate.default_schema: mscartoes
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
  instance:
    instance-id: ${spring.application.name}:${sping.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes
