spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: bootstrap
    password: bootstrap
    listener:
      simple:
        default-requeue-rejected: false
  datasource:
    url: jdbc:postgresql://localhost:5432/avaliador_credito
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate.default_schema: mscartoes
  flyway:
    enabled: true
    schemas: mscartoes
    default-schema: mscartoes
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8081/realms/mscourserealm


eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:ecok-pass-word-vai1@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${sping.application.instance_id:${random.value}}
    prefer-ip-address: true
    hostname: localhost

mq:
  queues:
    emissao-cartoes: emissao-cartoes